#!/usr/bin/env python3
"""
build_brand_card.py  ·  README.md + colors_and_type.css  ->  PASTE-INTO-TOOLS.md

PASTE-INTO-TOOLS.md is GENERATED. Never edit it. It replaces SKILL.md.

Why this exists
---------------
SKILL.md was the paste-into-a-tool version of the brand: the short card you give
a model that has no access to this repo. It was hand-copied from README.md, so
it rotted. Its own header admitted as much: "If this file and README.md
disagree, README.md wins and this file is stale." On 2026-08-12 it was stale,
still naming DM Serif Display eleven hours after that face was retired.

The function is worth keeping. A model handed 13 KB of prose follows it far less
reliably than one handed a short numbered card. The hand-maintained COPY is what
was not worth keeping.

So the card is now generated from two sources that cannot drift:

  README.md            the rules, written once, inside the canonical spec,
                       between <!-- CARD:START --> and <!-- CARD:END -->
  colors_and_type.css  the live values. Every hex and typeface in the card is
                       read from the stylesheet at build time, so the card is
                       incapable of naming a retired typeface or a stale hex.

Per ~/.claude/CLAUDE.md rule 2: anything that must always happen is a script.

Usage
-----
    python3 scripts/build_brand_card.py           # write the card
    python3 scripts/build_brand_card.py --check   # exit 1 if out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(__import__('pathlib').Path(__file__).resolve().parent))

from css_guard import CssGuardError, check as guard_css
from css_parse import find_block, declarations as parse_declarations


REPO = Path(__file__).resolve().parent.parent
CSS = REPO / "colors_and_type.css"
README = REPO / "README.md"
CARD = REPO / "PASTE-INTO-TOOLS.md"

START = "<!-- CARD:START -->"
END = "<!-- CARD:END -->"
DECL = re.compile(r"--([a-z0-9-]+)\s*:\s*([^;]+);", re.I)


def block(css: str, selector: str) -> str:
    """Comment- and string-aware. A comment mentioning the selector
    used to hijack this and hand back the wrong block."""
    return find_block(css, selector)


def declarations(body: str):
    return parse_declarations(body)


def primary(stack: str) -> str:
    return stack.split(",")[0].strip().strip("'\"")


def resolve(name: str, d: dict[str, str], seen=None) -> str:
    seen = seen or set()
    if name in seen:
        raise ValueError(f"circular reference at --{name}")
    seen.add(name)
    v = d[name]
    m = re.search(r"var\(\s*--([a-z0-9-]+)\s*\)", v)
    return resolve(m.group(1).lower(), d, seen) if m else v.strip()


def rules_from_readme() -> str:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit(
            f"README.md has no {START} / {END} markers. The card's rules live "
            f"inside README so there is only one copy of them. Add the markers "
            f"around the non-negotiables section and re-run."
        )
    return text.split(START, 1)[1].split(END, 1)[0].strip()


def build() -> str:
    guard_css(CSS)
    css = CSS.read_text(encoding="utf-8")
    root = declarations(block(css, ":root"))
    ink = declarations(block(css, '[data-surface="ink"]'))

    L = [
        "# drCWDugan brand card",
        "",
        "GENERATED by `scripts/build_brand_card.py`. Do not edit.",
        "Rules come from `README.md` between the CARD markers; every value below is",
        "read live from `colors_and_type.css`, so this file cannot name a retired",
        "typeface or a stale hex. Replaced the hand-maintained `SKILL.md` on 2026-08-12.",
        "",
        "Paste this file, plus `colors_and_type.css` and `tokens.json`, into any tool",
        "that needs to produce a drCWDugan asset.",
        "",
        "---",
        "",
        rules_from_readme(),
        "",
        "---",
        "",
        "## Live values, read from the stylesheet at build time",
        "",
        "### Typefaces",
        "",
        "| Role | Family | Token |",
        "|---|---|---|",
    ]
    for label, var in (("Display / headlines", "font-serif"),
                       ("Body, UI, eyebrows", "font-sans"),
                       ("Figures: every stat, CI, n =", "font-figures"),
                       ("Evidence voice, web", "font-mono"),
                       ("Evidence voice, rendered assets", "font-mono-asset")):
        if var in root:
            L.append(f"| {label} | **{primary(root[var])}** | `--{var}` |")

    L += ["", "### Core palette", "", "| Token | Value |", "|---|---|"]
    for var in ("grape-800", "grape-700", "grape-600", "grape-500",
                "grape-200", "grape-100", "ink-max", "ink-1000",
                "ink-700", "ink-500", "ink-200", "paper"):
        if var in root:
            L.append(f"| `--{var}` | `{root[var]}` |")

    L += ["", "### The two surfaces",
          "",
          "A component never hard-codes a colour. It reads `--surface-*` and inherits",
          "whichever surface it sits on. Set it on the card root:",
          "`<div class=\"slide\">` is paper, `<div class=\"slide\" data-surface=\"ink\">` is ink.",
          "",
          "| Token | paper | ink |", "|---|---|---|"]
    # the ink block overrides only the --surface-* names; the palette it points at
    # is declared in :root, so resolve the ink column against root plus the override
    ink_scope = {**root, **ink}
    for k in [k for k in root if k.startswith("surface")]:
        if k in ink:
            L.append(f"| `--{k}` | `{resolve(k, root)}` | `{resolve(k, ink_scope)}` |")

    L += ["", "### Scale",
          "",
          f"- Spacing: 4px base, `--space-1` {root.get('space-1','')} through "
          f"`--space-40` {root.get('space-40','')}",
          f"- Containers: narrow {root.get('container-narrow','')} (prose) · "
          f"default {root.get('container','')} · wide {root.get('container-wide','')}",
          f"- Radius: 0 default (editorial), {root.get('radius-md','')}/"
          f"{root.get('radius-lg','')}/{root.get('radius-xl','')} interactive, "
          f"{root.get('radius-pill','')} pills",
          f"- Display tracking {root.get('tracking-display','')}, body line-height "
          f"{root.get('lh-body','')}",
          ""]
    return "\n".join(L)


def main() -> int:
    try:
        rendered = build()
    except CssGuardError as e:
        print(str(e), file=sys.stderr)
        return 2

    if "--check" in sys.argv:
        if CARD.exists() and CARD.read_text(encoding="utf-8") == rendered:
            print(f"{CARD.name} is up to date")
            return 0
        print(f"{CARD.name} is STALE. Run: python3 scripts/build_brand_card.py",
              file=sys.stderr)
        return 1

    CARD.write_text(rendered, encoding="utf-8")
    print(f"wrote {CARD.name}  ({len(rendered)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
